
export const userTableQuery = 
`CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
   email VARCHAR(55) UNIQUE NOT NULL,
   username VARCHAR(55) UNIQUE NOT NULL,
   phoneNumber VARCHAR(255) UNIQUE NOT NULL,
   password VARCHAR(255) NOT NULL,
   role VARCHAR(45),
   imageUrl VARCHAR(200),
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   last_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
 ) `;



export const taskTableQuery=
`CREATE TABLE IF NOT EXISTS task
 (id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(55) ,
 file VARCHAR(255) ,
 description VARCHAR(100),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 last_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 userId INT NOT NULL ,
 FOREIGN KEY(userId) REFERENCES user(id)
  ON DELETE CASCADE
)`




